"""
Script to generate wing_mesh.py file
Creates a simple rectangular wing mesh using OpenAeroStruct
"""

# =============================================================================
# External Python modules
# =============================================================================
import numpy as np
from openaerostruct.meshing.mesh_generator import generate_mesh

# =============================================================================
# Local modules
# =============================================================================
from write_dict_to_py import write_array_to_py

# Create a rectangular wing mesh
# Based on the test usage, this should be an 11x7x3 mesh
mesh_dict = {
    "num_y": 13,      # Results in 7 spanwise points
    "num_x": 11,     # Results in 11 chordwise points
    "wing_type": "rect",
    "symmetry": True,
    "span": 10.0,
    "root_chord": 1.0,
    "span_cos_spacing": 0.0,
    "chord_cos_spacing": 0.0,
}

mesh = generate_mesh(mesh_dict)
print(mesh[0])
# Write as a plain text Python file
output_file = "../wing_mesh.py"

write_array_to_py(
    output_file,
    mesh,
    var_name='mesh',
    description=f'Generated by make_wing_mesh.py - Rectangular wing mesh (shape: {mesh.shape})'
)

print(f"Generated {output_file}")
print(f"Mesh shape: {mesh.shape}")
