C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 15 Jan 2021 14:26
C
C  Differentiation of cdcl in reverse (adjoint) mode (with options i4 dr8 r8):
C   gradient     of useful results: cd_cl cd cdclpol
C   with respect to varying inputs: cl cdclpol
C***********************************************************************
C    Module:  cdcl.f
C 
C    Copyright (C) 2020 Mark Drela, Harold Youngren
C 
C    This program is free software; you can redistribute it and/or modify
C    it under the terms of the GNU General Public License as published by
C    the Free Software Foundation; either version 2 of the License, or
C    (at your option) any later version.
C
C    This program is distributed in the hope that it will be useful,
C    but WITHOUT ANY WARRANTY; without even the implied warranty of
C    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
C    GNU General Public License for more details.
C
C    You should have received a copy of the GNU General Public License
C    along with this program; if not, write to the Free Software
C    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
C***********************************************************************
C
      SUBROUTINE CDCL_B(cdclpol, cdclpol_diff, cl, cl_diff, cd, cd_diff
     +                  , cd_cl, cd_cl_diff)
C-------------------------------------------------------------------------
C    Returns cd as a function of cl, or drag polar.
C
C    The polar is defined in 4 pieces, between and outside 3 cl,cd pairs,
C    shown as x symbols on diagram below
C
C     1) negative stall region
C     2) parabolic cd(cl) region between negative stall and the drag minimum
C     2) parabolic cd(cl) region between the drag minimum and positive stall
C     4) positive stall region
C
C             clpos,cdpos       <-  region 4 (quadratic above clpos)
C    cl |     x--------      
C       |    /                     
C       |   |                   <-  region 3 (quadratic above clcdmin)
C       |   x clcdmin,cdmin  
C       |   |                
C       |    \                  <-  region 2 (quadratic below clcdmin)
C       |     x_________      
C       |     clneg,cdneg       <-  region 1 (quadratic below clneg)
C       |                             
C       -------------------------
C                       cd
C
C    The 3 cd,cl pairs are specified in the input cdclpol(.) array:
C      cdclpol(1)   cl (clneg) at point before the negative stall drag rise
C      cdclpol(2)   cd (cdneg) at clneg
C      cdclpol(3)   cl (clcdmin) at minimum drag (middle of polar)
C      cdclpol(4)   cd (cdmin) at clcdmin
C      cdclpol(5)   cl (clpos) at point before the positive stall drag rise
C      cdclpol(6)   cd (cdpos) at clpos
C-------------------------------------------------------------------------
      REAL cdclpol(6)
      REAL cdclpol_diff(6)
      REAL clmin
      REAL clmin_diff
      REAL cdmin
      REAL cdmin_diff
      REAL cl0
      REAL cl0_diff
      REAL cd0
      REAL cd0_diff
      REAL clmax
      REAL clmax_diff
      REAL cdmax
      REAL cdmax_diff
      REAL cdx1
      REAL cdx1_diff
      REAL cdx2
      REAL cdx2_diff
      REAL clfac
      REAL temp
      REAL temp_diff
      REAL temp0
      REAL temp_diff0
      REAL temp1
      REAL temp_diff1
      REAL temp_diff2
      REAL clinc
      REAL cd_cl
      REAL cd_cl_diff
      REAL cd
      REAL cd_diff
      REAL cl
      REAL cl_diff
      REAL cdinc
C
C--- clinc and cdinc control the rate of increase of drag in the stall regions
C    clinc=0.2 forces drag to increase by cdinc over deltacl=0.2 after stall
C    the cdinc term is the cd increment added by deltacl=clinc after stall
      DATA clinc, cdinc /0.2, 0.0500/
C
C
C---- unpack the cd,cl parameters for the polar
      clmin = cdclpol(1)
      cdmin = cdclpol(2)
      cl0 = cdclpol(3)
      cd0 = cdclpol(4)
      clmax = cdclpol(5)
      cdmax = cdclpol(6)
      IF (clmax .LE. cl0 .OR. cl0 .LE. clmin) THEN
        cl_diff = 0.D0
        clmin_diff = 0.D0
        cl0_diff = 0.D0
        cdmax_diff = 0.D0
        clmax_diff = 0.D0
        cd0_diff = 0.D0
        cdmin_diff = 0.D0
      ELSE
C
C---- matching parameters that make the slopes smooth at the stall joins
        cdx1 = 2.0*(cdmin-cd0)*(clmin-cl0)/(clmin-cl0)**2
        cdx2 = 2.0*(cdmax-cd0)*(clmax-cl0)/(clmax-cl0)**2
        clfac = 1.0/clinc
C
        IF (cl .LT. clmin) THEN
          temp = (cl-cl0)/(clmin-cl0)
          temp_diff1 = cdinc*2.0*clfac**2*cd_cl_diff
          temp_diff0 = -(cd_cl_diff/(clmin-cl0))
          cdx1_diff = temp_diff0 + (1.0-temp)*cd_diff
          temp_diff = -(cdx1*temp_diff0/(clmin-cl0))
          clmin_diff = temp_diff - temp_diff1
          cl0_diff = -temp_diff
          cdmin_diff = cd_diff
          temp_diff0 = 2*(cl-clmin)*cdinc*clfac**2*cd_diff
          temp_diff = -(cdx1*cd_diff/(clmin-cl0))
          cl_diff = temp_diff1 + temp_diff + temp_diff0
          temp_diff1 = -(temp*temp_diff)
          cl0_diff = cl0_diff - temp_diff - temp_diff1
          clmin_diff = clmin_diff + temp_diff1 - temp_diff0
          cdmax_diff = 0.D0
          cdx2_diff = 0.D0
          clmax_diff = 0.D0
          cd0_diff = 0.D0
        ELSE
          IF (cl .LT. cl0) THEN
            temp_diff2 = 2.0*cd_cl_diff/(clmin-cl0)**2
            temp_diff1 = -(2*(cdmin-cd0)*(cl-cl0)*temp_diff2/(clmin-cl0)
     +        )
            cl0_diff = -((cdmin-cd0)*temp_diff2) - temp_diff1
            clmin_diff = temp_diff1
            temp0 = (cl-cl0)*(cl-cl0)
            temp_diff1 = cd_diff/(clmin-cl0)**2
            cdmin_diff = (cl-cl0)*temp_diff2 + temp0*temp_diff1
            cd0_diff = cd_diff - (cl-cl0)*temp_diff2 - temp0*temp_diff1
            temp_diff = 2*(cl-cl0)*(cdmin-cd0)*temp_diff1
            cl_diff = (cdmin-cd0)*temp_diff2 + temp_diff
            temp_diff2 = -(2*(cdmin-cd0)*temp0*temp_diff1/(clmin-cl0))
            clmin_diff = clmin_diff + temp_diff2
            cl0_diff = cl0_diff - temp_diff2 - temp_diff
            cdmax_diff = 0.D0
            cdx2_diff = 0.D0
            clmax_diff = 0.D0
          ELSE
            IF (cl .LT. clmax) THEN
              temp_diff2 = 2.0*cd_cl_diff/(clmax-cl0)**2
              cdmax_diff = (cl-cl0)*temp_diff2
              cd0_diff = -((cl-cl0)*temp_diff2)
              cl_diff = (cdmax-cd0)*temp_diff2
              cl0_diff = -((cdmax-cd0)*temp_diff2)
              temp_diff1 = -(2*(cdmax-cd0)*(cl-cl0)*temp_diff2/(clmax-
     +          cl0))
              temp1 = (cl-cl0)*(cl-cl0)
              temp_diff2 = cd_diff/(clmax-cl0)**2
              cd0_diff = cd0_diff + cd_diff - temp1*temp_diff2
              cdmax_diff = cdmax_diff + temp1*temp_diff2
              temp_diff0 = 2*(cl-cl0)*(cdmax-cd0)*temp_diff2
              temp_diff = -(2*(cdmax-cd0)*temp1*temp_diff2/(clmax-cl0))
              clmax_diff = temp_diff1 + temp_diff
              cl0_diff = cl0_diff - temp_diff1 - temp_diff - temp_diff0
              cl_diff = cl_diff + temp_diff0
              cdx2_diff = 0.D0
            ELSE
              temp1 = (cl-cl0)/(clmax-cl0)
              temp_diff2 = cdinc*2.0*clfac**2*cd_cl_diff
              temp_diff1 = cd_cl_diff/(clmax-cl0)
              cdx2_diff = temp_diff1 - (1.0-temp1)*cd_diff
              temp_diff0 = -(cdx2*temp_diff1/(clmax-cl0))
              clmax_diff = temp_diff0 - temp_diff2
              cl0_diff = -temp_diff0
              cl_diff = temp_diff2
              cdmax_diff = cd_diff
              temp_diff2 = 2*(cl-clmax)*cdinc*clfac**2*cd_diff
              temp_diff1 = cdx2*cd_diff/(clmax-cl0)
              cl_diff = cl_diff + temp_diff1 + temp_diff2
              temp_diff0 = -(temp1*temp_diff1)
              cl0_diff = cl0_diff - temp_diff1 - temp_diff0
              clmax_diff = clmax_diff + temp_diff0 - temp_diff2
              cd0_diff = 0.D0
            END IF
            clmin_diff = 0.D0
            cdmin_diff = 0.D0
          END IF
          cdx1_diff = 0.D0
        END IF
        temp_diff0 = 2.0*cdx2_diff/(clmax-cl0)
        cdmax_diff = cdmax_diff + temp_diff0
        temp_diff = -((cdmax-cd0)*temp_diff0/(clmax-cl0))
        clmax_diff = clmax_diff + temp_diff
        cl0_diff = cl0_diff - temp_diff
        temp_diff = 2.0*cdx1_diff/(clmin-cl0)
        cd0_diff = cd0_diff - temp_diff0 - temp_diff
        cdmin_diff = cdmin_diff + temp_diff
        temp_diff0 = -((cdmin-cd0)*temp_diff/(clmin-cl0))
        clmin_diff = clmin_diff + temp_diff0
        cl0_diff = cl0_diff - temp_diff0
      END IF
      cdclpol_diff(6) = cdclpol_diff(6) + cdmax_diff
      cdclpol_diff(5) = cdclpol_diff(5) + clmax_diff
      cdclpol_diff(4) = cdclpol_diff(4) + cd0_diff
      cdclpol_diff(3) = cdclpol_diff(3) + cl0_diff
      cdclpol_diff(2) = cdclpol_diff(2) + cdmin_diff
      cdclpol_diff(1) = cdclpol_diff(1) + clmin_diff
      END
C cdcl

