"""Auto-generated geometry file for aircraft_L1
Generated by make_aircraft_L1.py
"""
import numpy as np

input_dict = {
    "title": "MACH MDAO AVL",
    "mach": np.float64(0.0),
    "iysym": np.int32(0),
    "izsym": np.int32(0),
    "zsym": np.float64(0.0),
    "Sref": np.float64(1.13),
    "Cref": np.float64(0.4),
    "Bref": np.float64(1.0),
    "XYZref": np.array([0.0, 0.0, 0.0], dtype=np.float64),
    "CDp": np.float64(0.0),
    "surfaces": {
        "Wing": {
            "scale": np.array([1.0, 1.0, 1.0], dtype=np.float64),
            "translate": np.array([0.0, 0.0, 0.0], dtype=np.float64),
            "mesh": np.array([[[0.0, -0.0, 0.0], [0.0, 0.5, 0.0], [0.0, 1.0, 0.0]], [[0.19999999999999998, -0.0, 0.0], [0.135, 0.5, 0.0], [0.06999999999999999, 1.0, 0.0]], [[0.4, -0.0, 0.0], [0.27, 0.5, 0.0], [0.13999999999999999, 1.0, 0.0]]], dtype=np.float64),
        },
        "Horizontal Tail": {
            "scale": np.array([1.0, 1.0, 1.0], dtype=np.float64),
            "translate": np.array([0.0, 0.0, 0.0], dtype=np.float64),
            "mesh": np.array([[[1.5, -0.0, 0.0], [1.5, 0.5, 0.0]], [[1.5079533161020375, -0.0, 0.0], [1.5079533161020375, 0.5, 0.0]], [[1.531034738414071, -0.0, 0.0], [1.531034738414071, 0.5, 0.0]], [[1.566984896502473, -0.0, 0.0], [1.566984896502473, 0.5, 0.0]], [[1.612284738414071, -0.0, 0.0], [1.612284738414071, 0.5, 0.0]], [[1.6625, -0.0, 0.0], [1.6625, 0.5, 0.0]], [[1.712715261585929, -0.0, 0.0], [1.712715261585929, 0.5, 0.0]], [[1.7580151034975269, -0.0, 0.0], [1.7580151034975269, 0.5, 0.0]], [[1.793965261585929, -0.0, 0.0], [1.793965261585929, 0.5, 0.0]], [[1.8170466838979624, -0.0, 0.0], [1.8170466838979624, 0.5, 0.0]], [[1.825, -0.0, 0.0], [1.825, 0.5, 0.0]]], dtype=np.float64),
            "control_assignments": {
                "Elevator": {
                    "assignment": np.array([0, 1], dtype=np.int64),
                    "xhinged": 0.0,
                    "vhinged": np.array([0, 1, 0], dtype=np.int64),
                    "gaind": -1.0,
                    "refld": 1.0,
                },
            },
        },
    },
    "dname": ['Elevator'],
}
