"""Auto-generated geometry file
Generated by make_rect_with_body.py - Rectangular wing with fuselage body
"""
import numpy as np

input_dict = {
    "title": "MACH MDAO AVL",
    "mach": np.float64(0.0),
    "iysym": np.int32(0),
    "izsym": np.int32(0),
    "zsym": np.float64(0.0),
    "Sref": np.float64(1.123),
    "Cref": np.float64(0.25),
    "Bref": np.float64(6.01),
    "XYZref": np.array([0.0, 0.0, 0.0], dtype=np.float64),
    "CDp": np.float64(0.0),
    "surfaces": {
        "Wing": {
            "scale": np.array([1.0, 1.0, 1.0], dtype=np.float64),
            "translate": np.array([0.0, 0.0, 0.0], dtype=np.float64),
            "mesh": np.array([[[0.0, 0.0, 1.0], [0.0, 1.0, 1.0]], [[1.0, 0.0, 1.0], [1.0, 1.0, 1.0]]], dtype=np.float64),
            "control_assignments": {
                "Elevator": {
                    "assignment": np.array([0, 1], dtype=np.int64),
                    "xhinged": 0.5,
                    "vhinged": np.array([0, 1, 0], dtype=np.int64),
                    "gaind": -1.0,
                    "refld": 1.0,
                },
            },
        },
    },
    "bodies": {
        "Fuse pod": {
            "scale": np.array([1.0, 1.0, 1.0], dtype=np.float64),
            "translate": np.array([0.0, 0.0, 0.0], dtype=np.float64),
            "nvb": np.int32(4),
            "bspace": np.float64(2.0),
            "bfile": "../geom_files/fuseSimple.dat",
        },
    },
    "dname": ['Elevator'],
}
